name: country_flags
description: A Flutter package to show a flag icon from a ISO country code.
version: 2.0.0
homepage: https://github.com/arturograu/country_flags
repository: https://github.com/arturograu/country_flags

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.1
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ">=3.0.1 <5.0.0"

flutter:
  assets:
    - res/

